// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE78_OS_Command_Injection__char_console_execl_10_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_03_good();

	void CWE78_OS_Command_Injection__char_console_execlp_14_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_13_good();

	void CWE78_OS_Command_Injection__char_console_execlp_68_good();

	void CWE78_OS_Command_Injection__char_console_execlp_65_good();

	void CWE78_OS_Command_Injection__char_console_execlp_13_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_53_good();

	void CWE78_OS_Command_Injection__char_console_execl_03_good();

	void CWE78_OS_Command_Injection__char_console_execlp_34_good();

	void CWE78_OS_Command_Injection__char_console_execl_11_good();

	void CWE78_OS_Command_Injection__char_console_execl_12_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_32_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_67_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_22_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_17_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_34_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_42_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_15_good();

	void CWE78_OS_Command_Injection__char_console_execlp_09_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_09_good();

	void CWE78_OS_Command_Injection__char_console_execl_54_good();

	void CWE78_OS_Command_Injection__char_console_execl_21_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_41_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_02_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_03_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_63_good();

	void CWE78_OS_Command_Injection__char_console_execl_14_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_09_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_17_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_10_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_10_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_54_good();

	void CWE78_OS_Command_Injection__char_console_execlp_01_good();

	void CWE78_OS_Command_Injection__char_console_execl_34_good();

	void CWE78_OS_Command_Injection__char_console_execlp_10_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_14_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_61_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_32_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_11_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_18_good();

	void CWE78_OS_Command_Injection__char_console_execlp_32_good();

	void CWE78_OS_Command_Injection__char_console_execl_08_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_12_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_65_good();

	void CWE78_OS_Command_Injection__char_console_execl_31_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_64_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_31_good();

	void CWE78_OS_Command_Injection__char_console_execlp_64_good();

	void CWE78_OS_Command_Injection__char_console_execlp_44_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_52_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_02_good();

	void CWE78_OS_Command_Injection__char_console_execlp_31_good();

	void CWE78_OS_Command_Injection__char_console_execl_61_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_22_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_44_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_53_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_44_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_16_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_13_good();

	void CWE78_OS_Command_Injection__char_console_execl_53_good();

	void CWE78_OS_Command_Injection__char_console_execl_64_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_65_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_21_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_07_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_04_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_66_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_12_good();

	void CWE78_OS_Command_Injection__char_console_execlp_66_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_05_good();

	void CWE78_OS_Command_Injection__char_console_execl_65_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_11_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_61_good();

	void CWE78_OS_Command_Injection__char_console_execlp_67_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_65_good();

	void CWE78_OS_Command_Injection__char_console_execlp_03_good();

	void CWE78_OS_Command_Injection__char_console_execlp_15_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_16_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_06_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_07_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_64_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_01_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_06_good();

	void CWE78_OS_Command_Injection__char_console_execl_06_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_44_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_68_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_66_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_21_good();

	void CWE78_OS_Command_Injection__char_console_execl_17_good();

	void CWE78_OS_Command_Injection__char_console_execl_44_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_45_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_18_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_68_good();

	void CWE78_OS_Command_Injection__char_console_execlp_06_good();

	void CWE78_OS_Command_Injection__char_console_execl_13_good();

	void CWE78_OS_Command_Injection__char_console_execlp_04_good();

	void CWE78_OS_Command_Injection__char_console_execlp_12_good();

	void CWE78_OS_Command_Injection__char_console_execl_32_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_67_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_22_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_09_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_34_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_51_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_11_good();

	void CWE78_OS_Command_Injection__char_console_execl_04_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_41_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_13_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_34_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_42_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_61_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_05_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_01_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_21_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_21_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_04_good();

	void CWE78_OS_Command_Injection__char_console_execl_01_good();

	void CWE78_OS_Command_Injection__char_console_execl_09_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_54_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_52_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_17_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_08_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_17_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_05_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_08_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_16_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_41_good();

	void CWE78_OS_Command_Injection__char_console_execl_66_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_66_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_11_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_54_good();

	void CWE78_OS_Command_Injection__char_console_execlp_53_good();

	void CWE78_OS_Command_Injection__char_console_execlp_07_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_22_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_15_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_07_good();

	void CWE78_OS_Command_Injection__char_console_execl_51_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_10_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_06_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_61_good();

	void CWE78_OS_Command_Injection__char_console_execlp_42_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_18_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_52_good();

	void CWE78_OS_Command_Injection__char_console_execl_15_good();

	void CWE78_OS_Command_Injection__char_console_execlp_41_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_14_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_03_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_51_good();

	void CWE78_OS_Command_Injection__char_console_execlp_54_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_66_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_51_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_54_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_45_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_65_good();

	void CWE78_OS_Command_Injection__char_console_execlp_45_good();

	void CWE78_OS_Command_Injection__char_console_execlp_51_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_07_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_15_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_12_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_41_good();

	void CWE78_OS_Command_Injection__char_console_execl_05_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_13_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_67_good();

	void CWE78_OS_Command_Injection__char_console_execlp_18_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_14_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_64_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_10_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_53_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_16_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_68_good();

	void CWE78_OS_Command_Injection__char_console_execl_42_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_67_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_63_good();

	void CWE78_OS_Command_Injection__char_console_execlp_05_good();

	void CWE78_OS_Command_Injection__char_console_execlp_02_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_42_good();

	void CWE78_OS_Command_Injection__char_console_execlp_08_good();

	void CWE78_OS_Command_Injection__char_console_execl_22_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_04_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_68_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_08_good();

	void CWE78_OS_Command_Injection__char_console_execlp_21_good();

	void CWE78_OS_Command_Injection__char_console_execlp_17_good();

	void CWE78_OS_Command_Injection__char_console_execl_45_good();

	void CWE78_OS_Command_Injection__char_console_execlp_22_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_08_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_09_good();

	void CWE78_OS_Command_Injection__char_console_execl_18_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_18_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_01_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_06_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_52_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_32_good();

	void CWE78_OS_Command_Injection__char_console_execl_63_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_02_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_15_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_51_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_31_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_31_good();

	void CWE78_OS_Command_Injection__char_console_execl_16_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_63_good();

	void CWE78_OS_Command_Injection__char_console_execlp_11_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_32_good();

	void CWE78_OS_Command_Injection__char_console_execlp_61_good();

	void CWE78_OS_Command_Injection__char_console_execl_41_good();

	void CWE78_OS_Command_Injection__char_console_execl_52_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_01_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_63_good();

	void CWE78_OS_Command_Injection__char_console_execlp_16_good();

	void CWE78_OS_Command_Injection__char_connect_socket_system_45_good();

	void CWE78_OS_Command_Injection__char_console_execl_02_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_03_good();

	void CWE78_OS_Command_Injection__char_console_execlp_63_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_44_good();

	void CWE78_OS_Command_Injection__char_console_execl_68_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_02_good();

	void CWE78_OS_Command_Injection__char_console_execl_07_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_45_good();

	void CWE78_OS_Command_Injection__char_console_execlp_52_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_04_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_53_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_14_good();

	void CWE78_OS_Command_Injection__char_console_execl_67_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_42_good();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_05_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_64_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_31_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_34_good();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_12_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE78_OS_Command_Injection__char_console_execl_10_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_03_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_14_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_13_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_68_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_65_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_13_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_53_bad();

	void CWE78_OS_Command_Injection__char_console_execl_03_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_34_bad();

	void CWE78_OS_Command_Injection__char_console_execl_11_bad();

	void CWE78_OS_Command_Injection__char_console_execl_12_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_32_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_67_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_22_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_17_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_34_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_42_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_15_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_09_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_09_bad();

	void CWE78_OS_Command_Injection__char_console_execl_54_bad();

	void CWE78_OS_Command_Injection__char_console_execl_21_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_41_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_02_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_03_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_63_bad();

	void CWE78_OS_Command_Injection__char_console_execl_14_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_09_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_17_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_10_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_10_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_54_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_01_bad();

	void CWE78_OS_Command_Injection__char_console_execl_34_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_10_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_14_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_61_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_32_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_11_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_18_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_32_bad();

	void CWE78_OS_Command_Injection__char_console_execl_08_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_12_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_65_bad();

	void CWE78_OS_Command_Injection__char_console_execl_31_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_64_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_31_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_64_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_44_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_52_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_02_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_31_bad();

	void CWE78_OS_Command_Injection__char_console_execl_61_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_22_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_44_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_53_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_44_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_16_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_13_bad();

	void CWE78_OS_Command_Injection__char_console_execl_53_bad();

	void CWE78_OS_Command_Injection__char_console_execl_64_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_65_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_21_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_07_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_04_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_66_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_12_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_66_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_05_bad();

	void CWE78_OS_Command_Injection__char_console_execl_65_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_11_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_61_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_67_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_65_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_03_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_15_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_16_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_06_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_07_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_64_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_01_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_06_bad();

	void CWE78_OS_Command_Injection__char_console_execl_06_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_44_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_68_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_66_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_21_bad();

	void CWE78_OS_Command_Injection__char_console_execl_17_bad();

	void CWE78_OS_Command_Injection__char_console_execl_44_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_45_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_18_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_68_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_06_bad();

	void CWE78_OS_Command_Injection__char_console_execl_13_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_04_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_12_bad();

	void CWE78_OS_Command_Injection__char_console_execl_32_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_67_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_22_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_09_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_34_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_51_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_11_bad();

	void CWE78_OS_Command_Injection__char_console_execl_04_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_41_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_13_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_34_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_42_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_61_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_05_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_01_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_21_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_21_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_04_bad();

	void CWE78_OS_Command_Injection__char_console_execl_01_bad();

	void CWE78_OS_Command_Injection__char_console_execl_09_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_54_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_52_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_17_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_08_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_17_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_05_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_08_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_16_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_41_bad();

	void CWE78_OS_Command_Injection__char_console_execl_66_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_66_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_11_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_54_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_53_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_07_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_22_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_15_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_07_bad();

	void CWE78_OS_Command_Injection__char_console_execl_51_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_10_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_06_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_61_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_42_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_18_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_52_bad();

	void CWE78_OS_Command_Injection__char_console_execl_15_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_41_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_14_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_03_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_51_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_54_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_66_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_51_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_54_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_45_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_65_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_45_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_51_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_07_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_15_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_12_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_41_bad();

	void CWE78_OS_Command_Injection__char_console_execl_05_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_13_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_67_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_18_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_14_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_64_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_10_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_53_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_16_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_68_bad();

	void CWE78_OS_Command_Injection__char_console_execl_42_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_67_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_63_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_05_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_02_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_42_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_08_bad();

	void CWE78_OS_Command_Injection__char_console_execl_22_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_04_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_68_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_08_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_21_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_17_bad();

	void CWE78_OS_Command_Injection__char_console_execl_45_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_22_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_08_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_09_bad();

	void CWE78_OS_Command_Injection__char_console_execl_18_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_18_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_01_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_06_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_52_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_32_bad();

	void CWE78_OS_Command_Injection__char_console_execl_63_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_02_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_15_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_51_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_31_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_31_bad();

	void CWE78_OS_Command_Injection__char_console_execl_16_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_63_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_11_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_32_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_61_bad();

	void CWE78_OS_Command_Injection__char_console_execl_41_bad();

	void CWE78_OS_Command_Injection__char_console_execl_52_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_01_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_63_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_16_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_system_45_bad();

	void CWE78_OS_Command_Injection__char_console_execl_02_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_03_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_63_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_44_bad();

	void CWE78_OS_Command_Injection__char_console_execl_68_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_02_bad();

	void CWE78_OS_Command_Injection__char_console_execl_07_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_45_bad();

	void CWE78_OS_Command_Injection__char_console_execlp_52_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_04_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_53_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_14_bad();

	void CWE78_OS_Command_Injection__char_console_execl_67_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_42_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_popen_05_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_64_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execlp_31_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_34_bad();

	void CWE78_OS_Command_Injection__char_connect_socket_execl_12_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
	namespace CWE78_OS_Command_Injection__char_connect_socket_system_74 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_62 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_62 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_73 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_82 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_81 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execl_72 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_43 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_72 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_74 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execl_33 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_62 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_43 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_81 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_74 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_73 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_62 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execl_81 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_73 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_33 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_74 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_43 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_72 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execl_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_81 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_74 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_72 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_81 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execl_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_73 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_72 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_82 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_72 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_33 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_33 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_82 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_62 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_81 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_82 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execl_62 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execl_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execl_82 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_43 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_73 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execl_73 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execl_43 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_82 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_33 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execl_74 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_43 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_execl_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_33 { void good();}

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
	namespace CWE78_OS_Command_Injection__char_connect_socket_system_74 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_62 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_62 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_73 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_82 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_81 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execl_72 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_43 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_72 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_74 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execl_33 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_62 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_43 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_81 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_74 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_73 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_62 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execl_81 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_73 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_33 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_74 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_43 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_72 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execl_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_81 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_74 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_72 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_81 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execl_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_73 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_72 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_82 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_72 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_33 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_33 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_82 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_62 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_81 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_82 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execlp_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execl_62 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execl_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execl_82 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_43 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_73 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execl_73 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execl_43 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execl_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_82 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_33 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execl_74 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_popen_43 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_system_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_execl_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_connect_socket_execlp_33 { void bad();}

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
