// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE78_OS_Command_Injection__char_console_system_02_good();

	void CWE78_OS_Command_Injection__char_environment_execl_31_good();

	void CWE78_OS_Command_Injection__char_console_popen_31_good();

	void CWE78_OS_Command_Injection__char_console_popen_22_good();

	void CWE78_OS_Command_Injection__char_console_popen_64_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_18_good();

	void CWE78_OS_Command_Injection__char_environment_system_05_good();

	void CWE78_OS_Command_Injection__char_environment_popen_08_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_22_good();

	void CWE78_OS_Command_Injection__char_environment_popen_53_good();

	void CWE78_OS_Command_Injection__char_console_popen_09_good();

	void CWE78_OS_Command_Injection__char_environment_execl_06_good();

	void CWE78_OS_Command_Injection__char_environment_execl_13_good();

	void CWE78_OS_Command_Injection__char_environment_execl_21_good();

	void CWE78_OS_Command_Injection__char_console_popen_66_good();

	void CWE78_OS_Command_Injection__char_environment_popen_01_good();

	void CWE78_OS_Command_Injection__char_environment_popen_03_good();

	void CWE78_OS_Command_Injection__char_environment_popen_61_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_04_good();

	void CWE78_OS_Command_Injection__char_environment_popen_17_good();

	void CWE78_OS_Command_Injection__char_environment_execl_64_good();

	void CWE78_OS_Command_Injection__char_environment_popen_18_good();

	void CWE78_OS_Command_Injection__char_environment_popen_32_good();

	void CWE78_OS_Command_Injection__char_console_system_16_good();

	void CWE78_OS_Command_Injection__char_console_system_34_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_53_good();

	void CWE78_OS_Command_Injection__char_console_popen_07_good();

	void CWE78_OS_Command_Injection__char_environment_system_45_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_52_good();

	void CWE78_OS_Command_Injection__char_environment_execl_34_good();

	void CWE78_OS_Command_Injection__char_environment_system_65_good();

	void CWE78_OS_Command_Injection__char_console_system_45_good();

	void CWE78_OS_Command_Injection__char_environment_system_42_good();

	void CWE78_OS_Command_Injection__char_environment_execl_18_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_51_good();

	void CWE78_OS_Command_Injection__char_environment_popen_44_good();

	void CWE78_OS_Command_Injection__char_console_popen_15_good();

	void CWE78_OS_Command_Injection__char_console_popen_54_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_11_good();

	void CWE78_OS_Command_Injection__char_environment_execl_53_good();

	void CWE78_OS_Command_Injection__char_console_system_09_good();

	void CWE78_OS_Command_Injection__char_console_system_67_good();

	void CWE78_OS_Command_Injection__char_console_popen_06_good();

	void CWE78_OS_Command_Injection__char_environment_execl_67_good();

	void CWE78_OS_Command_Injection__char_environment_system_06_good();

	void CWE78_OS_Command_Injection__char_environment_execl_08_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_09_good();

	void CWE78_OS_Command_Injection__char_environment_popen_67_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_64_good();

	void CWE78_OS_Command_Injection__char_environment_system_02_good();

	void CWE78_OS_Command_Injection__char_environment_execl_51_good();

	void CWE78_OS_Command_Injection__char_environment_execl_66_good();

	void CWE78_OS_Command_Injection__char_console_popen_44_good();

	void CWE78_OS_Command_Injection__char_console_system_54_good();

	void CWE78_OS_Command_Injection__char_environment_system_51_good();

	void CWE78_OS_Command_Injection__char_environment_popen_13_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_12_good();

	void CWE78_OS_Command_Injection__char_environment_popen_65_good();

	void CWE78_OS_Command_Injection__char_environment_execl_04_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_21_good();

	void CWE78_OS_Command_Injection__char_console_popen_65_good();

	void CWE78_OS_Command_Injection__char_console_system_14_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_67_good();

	void CWE78_OS_Command_Injection__char_environment_popen_34_good();

	void CWE78_OS_Command_Injection__char_console_system_68_good();

	void CWE78_OS_Command_Injection__char_console_system_03_good();

	void CWE78_OS_Command_Injection__char_environment_system_10_good();

	void CWE78_OS_Command_Injection__char_console_popen_61_good();

	void CWE78_OS_Command_Injection__char_environment_execl_07_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_63_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_32_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_05_good();

	void CWE78_OS_Command_Injection__char_console_popen_63_good();

	void CWE78_OS_Command_Injection__char_environment_system_16_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_03_good();

	void CWE78_OS_Command_Injection__char_console_system_13_good();

	void CWE78_OS_Command_Injection__char_console_popen_05_good();

	void CWE78_OS_Command_Injection__char_environment_popen_02_good();

	void CWE78_OS_Command_Injection__char_environment_execl_41_good();

	void CWE78_OS_Command_Injection__char_console_popen_18_good();

	void CWE78_OS_Command_Injection__char_console_system_52_good();

	void CWE78_OS_Command_Injection__char_console_system_05_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_61_good();

	void CWE78_OS_Command_Injection__char_environment_execl_16_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_41_good();

	void CWE78_OS_Command_Injection__char_environment_system_21_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_45_good();

	void CWE78_OS_Command_Injection__char_environment_execl_01_good();

	void CWE78_OS_Command_Injection__char_environment_system_12_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_44_good();

	void CWE78_OS_Command_Injection__char_console_popen_52_good();

	void CWE78_OS_Command_Injection__char_environment_execl_09_good();

	void CWE78_OS_Command_Injection__char_environment_popen_64_good();

	void CWE78_OS_Command_Injection__char_environment_system_53_good();

	void CWE78_OS_Command_Injection__char_console_system_42_good();

	void CWE78_OS_Command_Injection__char_console_popen_13_good();

	void CWE78_OS_Command_Injection__char_environment_popen_11_good();

	void CWE78_OS_Command_Injection__char_console_system_31_good();

	void CWE78_OS_Command_Injection__char_console_system_61_good();

	void CWE78_OS_Command_Injection__char_environment_popen_63_good();

	void CWE78_OS_Command_Injection__char_console_popen_17_good();

	void CWE78_OS_Command_Injection__char_environment_system_64_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_34_good();

	void CWE78_OS_Command_Injection__char_environment_system_01_good();

	void CWE78_OS_Command_Injection__char_environment_system_63_good();

	void CWE78_OS_Command_Injection__char_console_system_64_good();

	void CWE78_OS_Command_Injection__char_console_popen_02_good();

	void CWE78_OS_Command_Injection__char_console_system_07_good();

	void CWE78_OS_Command_Injection__char_console_system_12_good();

	void CWE78_OS_Command_Injection__char_environment_popen_14_good();

	void CWE78_OS_Command_Injection__char_environment_execl_11_good();

	void CWE78_OS_Command_Injection__char_environment_system_31_good();

	void CWE78_OS_Command_Injection__char_console_popen_45_good();

	void CWE78_OS_Command_Injection__char_environment_execl_68_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_10_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_01_good();

	void CWE78_OS_Command_Injection__char_environment_popen_06_good();

	void CWE78_OS_Command_Injection__char_environment_execl_02_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_42_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_65_good();

	void CWE78_OS_Command_Injection__char_console_popen_32_good();

	void CWE78_OS_Command_Injection__char_environment_popen_05_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_02_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_13_good();

	void CWE78_OS_Command_Injection__char_environment_system_04_good();

	void CWE78_OS_Command_Injection__char_environment_system_11_good();

	void CWE78_OS_Command_Injection__char_environment_execl_14_good();

	void CWE78_OS_Command_Injection__char_environment_popen_12_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_16_good();

	void CWE78_OS_Command_Injection__char_environment_execl_32_good();

	void CWE78_OS_Command_Injection__char_environment_execl_22_good();

	void CWE78_OS_Command_Injection__char_console_popen_34_good();

	void CWE78_OS_Command_Injection__char_environment_popen_41_good();

	void CWE78_OS_Command_Injection__char_environment_execl_05_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_68_good();

	void CWE78_OS_Command_Injection__char_console_popen_68_good();

	void CWE78_OS_Command_Injection__char_environment_popen_09_good();

	void CWE78_OS_Command_Injection__char_environment_system_61_good();

	void CWE78_OS_Command_Injection__char_environment_system_18_good();

	void CWE78_OS_Command_Injection__char_environment_execl_10_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_14_good();

	void CWE78_OS_Command_Injection__char_console_system_65_good();

	void CWE78_OS_Command_Injection__char_environment_execl_42_good();

	void CWE78_OS_Command_Injection__char_environment_popen_54_good();

	void CWE78_OS_Command_Injection__char_environment_system_54_good();

	void CWE78_OS_Command_Injection__char_console_system_44_good();

	void CWE78_OS_Command_Injection__char_environment_system_15_good();

	void CWE78_OS_Command_Injection__char_environment_popen_22_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_08_good();

	void CWE78_OS_Command_Injection__char_environment_system_09_good();

	void CWE78_OS_Command_Injection__char_console_system_06_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_17_good();

	void CWE78_OS_Command_Injection__char_console_system_17_good();

	void CWE78_OS_Command_Injection__char_console_system_51_good();

	void CWE78_OS_Command_Injection__char_console_system_08_good();

	void CWE78_OS_Command_Injection__char_environment_execl_17_good();

	void CWE78_OS_Command_Injection__char_console_system_41_good();

	void CWE78_OS_Command_Injection__char_environment_popen_52_good();

	void CWE78_OS_Command_Injection__char_environment_system_17_good();

	void CWE78_OS_Command_Injection__char_console_popen_11_good();

	void CWE78_OS_Command_Injection__char_environment_popen_15_good();

	void CWE78_OS_Command_Injection__char_environment_execl_15_good();

	void CWE78_OS_Command_Injection__char_environment_system_66_good();

	void CWE78_OS_Command_Injection__char_environment_system_14_good();

	void CWE78_OS_Command_Injection__char_environment_system_41_good();

	void CWE78_OS_Command_Injection__char_environment_popen_21_good();

	void CWE78_OS_Command_Injection__char_environment_execl_63_good();

	void CWE78_OS_Command_Injection__char_console_system_53_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_06_good();

	void CWE78_OS_Command_Injection__char_console_popen_21_good();

	void CWE78_OS_Command_Injection__char_console_system_01_good();

	void CWE78_OS_Command_Injection__char_environment_system_67_good();

	void CWE78_OS_Command_Injection__char_environment_system_68_good();

	void CWE78_OS_Command_Injection__char_console_system_21_good();

	void CWE78_OS_Command_Injection__char_environment_system_13_good();

	void CWE78_OS_Command_Injection__char_environment_execl_61_good();

	void CWE78_OS_Command_Injection__char_environment_execl_45_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_15_good();

	void CWE78_OS_Command_Injection__char_environment_popen_04_good();

	void CWE78_OS_Command_Injection__char_environment_system_08_good();

	void CWE78_OS_Command_Injection__char_console_system_04_good();

	void CWE78_OS_Command_Injection__char_console_popen_08_good();

	void CWE78_OS_Command_Injection__char_environment_execl_44_good();

	void CWE78_OS_Command_Injection__char_console_popen_03_good();

	void CWE78_OS_Command_Injection__char_environment_popen_68_good();

	void CWE78_OS_Command_Injection__char_environment_system_34_good();

	void CWE78_OS_Command_Injection__char_console_popen_41_good();

	void CWE78_OS_Command_Injection__char_environment_popen_10_good();

	void CWE78_OS_Command_Injection__char_console_popen_51_good();

	void CWE78_OS_Command_Injection__char_environment_execl_52_good();

	void CWE78_OS_Command_Injection__char_environment_popen_31_good();

	void CWE78_OS_Command_Injection__char_environment_system_52_good();

	void CWE78_OS_Command_Injection__char_console_system_63_good();

	void CWE78_OS_Command_Injection__char_environment_popen_66_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_66_good();

	void CWE78_OS_Command_Injection__char_console_popen_04_good();

	void CWE78_OS_Command_Injection__char_console_system_10_good();

	void CWE78_OS_Command_Injection__char_console_popen_16_good();

	void CWE78_OS_Command_Injection__char_console_popen_42_good();

	void CWE78_OS_Command_Injection__char_console_system_11_good();

	void CWE78_OS_Command_Injection__char_environment_system_32_good();

	void CWE78_OS_Command_Injection__char_environment_execl_65_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_07_good();

	void CWE78_OS_Command_Injection__char_console_system_22_good();

	void CWE78_OS_Command_Injection__char_console_popen_10_good();

	void CWE78_OS_Command_Injection__char_environment_execl_54_good();

	void CWE78_OS_Command_Injection__char_console_system_15_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_31_good();

	void CWE78_OS_Command_Injection__char_environment_system_44_good();

	void CWE78_OS_Command_Injection__char_environment_popen_45_good();

	void CWE78_OS_Command_Injection__char_console_system_66_good();

	void CWE78_OS_Command_Injection__char_environment_execlp_54_good();

	void CWE78_OS_Command_Injection__char_console_system_32_good();

	void CWE78_OS_Command_Injection__char_console_popen_01_good();

	void CWE78_OS_Command_Injection__char_console_system_18_good();

	void CWE78_OS_Command_Injection__char_environment_system_03_good();

	void CWE78_OS_Command_Injection__char_environment_system_07_good();

	void CWE78_OS_Command_Injection__char_console_popen_53_good();

	void CWE78_OS_Command_Injection__char_console_popen_12_good();

	void CWE78_OS_Command_Injection__char_environment_execl_12_good();

	void CWE78_OS_Command_Injection__char_environment_execl_03_good();

	void CWE78_OS_Command_Injection__char_console_popen_14_good();

	void CWE78_OS_Command_Injection__char_environment_popen_51_good();

	void CWE78_OS_Command_Injection__char_environment_system_22_good();

	void CWE78_OS_Command_Injection__char_environment_popen_16_good();

	void CWE78_OS_Command_Injection__char_environment_popen_07_good();

	void CWE78_OS_Command_Injection__char_console_popen_67_good();

	void CWE78_OS_Command_Injection__char_environment_popen_42_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE78_OS_Command_Injection__char_console_system_02_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_31_bad();

	void CWE78_OS_Command_Injection__char_console_popen_31_bad();

	void CWE78_OS_Command_Injection__char_console_popen_22_bad();

	void CWE78_OS_Command_Injection__char_console_popen_64_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_18_bad();

	void CWE78_OS_Command_Injection__char_environment_system_05_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_08_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_22_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_53_bad();

	void CWE78_OS_Command_Injection__char_console_popen_09_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_06_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_13_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_21_bad();

	void CWE78_OS_Command_Injection__char_console_popen_66_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_01_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_03_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_61_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_04_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_17_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_64_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_18_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_32_bad();

	void CWE78_OS_Command_Injection__char_console_system_16_bad();

	void CWE78_OS_Command_Injection__char_console_system_34_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_53_bad();

	void CWE78_OS_Command_Injection__char_console_popen_07_bad();

	void CWE78_OS_Command_Injection__char_environment_system_45_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_52_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_34_bad();

	void CWE78_OS_Command_Injection__char_environment_system_65_bad();

	void CWE78_OS_Command_Injection__char_console_system_45_bad();

	void CWE78_OS_Command_Injection__char_environment_system_42_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_18_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_51_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_44_bad();

	void CWE78_OS_Command_Injection__char_console_popen_15_bad();

	void CWE78_OS_Command_Injection__char_console_popen_54_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_11_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_53_bad();

	void CWE78_OS_Command_Injection__char_console_system_09_bad();

	void CWE78_OS_Command_Injection__char_console_system_67_bad();

	void CWE78_OS_Command_Injection__char_console_popen_06_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_67_bad();

	void CWE78_OS_Command_Injection__char_environment_system_06_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_08_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_09_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_67_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_64_bad();

	void CWE78_OS_Command_Injection__char_environment_system_02_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_51_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_66_bad();

	void CWE78_OS_Command_Injection__char_console_popen_44_bad();

	void CWE78_OS_Command_Injection__char_console_system_54_bad();

	void CWE78_OS_Command_Injection__char_environment_system_51_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_13_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_12_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_65_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_04_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_21_bad();

	void CWE78_OS_Command_Injection__char_console_popen_65_bad();

	void CWE78_OS_Command_Injection__char_console_system_14_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_67_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_34_bad();

	void CWE78_OS_Command_Injection__char_console_system_68_bad();

	void CWE78_OS_Command_Injection__char_console_system_03_bad();

	void CWE78_OS_Command_Injection__char_environment_system_10_bad();

	void CWE78_OS_Command_Injection__char_console_popen_61_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_07_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_63_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_32_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_05_bad();

	void CWE78_OS_Command_Injection__char_console_popen_63_bad();

	void CWE78_OS_Command_Injection__char_environment_system_16_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_03_bad();

	void CWE78_OS_Command_Injection__char_console_system_13_bad();

	void CWE78_OS_Command_Injection__char_console_popen_05_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_02_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_41_bad();

	void CWE78_OS_Command_Injection__char_console_popen_18_bad();

	void CWE78_OS_Command_Injection__char_console_system_52_bad();

	void CWE78_OS_Command_Injection__char_console_system_05_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_61_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_16_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_41_bad();

	void CWE78_OS_Command_Injection__char_environment_system_21_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_45_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_01_bad();

	void CWE78_OS_Command_Injection__char_environment_system_12_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_44_bad();

	void CWE78_OS_Command_Injection__char_console_popen_52_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_09_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_64_bad();

	void CWE78_OS_Command_Injection__char_environment_system_53_bad();

	void CWE78_OS_Command_Injection__char_console_system_42_bad();

	void CWE78_OS_Command_Injection__char_console_popen_13_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_11_bad();

	void CWE78_OS_Command_Injection__char_console_system_31_bad();

	void CWE78_OS_Command_Injection__char_console_system_61_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_63_bad();

	void CWE78_OS_Command_Injection__char_console_popen_17_bad();

	void CWE78_OS_Command_Injection__char_environment_system_64_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_34_bad();

	void CWE78_OS_Command_Injection__char_environment_system_01_bad();

	void CWE78_OS_Command_Injection__char_environment_system_63_bad();

	void CWE78_OS_Command_Injection__char_console_system_64_bad();

	void CWE78_OS_Command_Injection__char_console_popen_02_bad();

	void CWE78_OS_Command_Injection__char_console_system_07_bad();

	void CWE78_OS_Command_Injection__char_console_system_12_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_14_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_11_bad();

	void CWE78_OS_Command_Injection__char_environment_system_31_bad();

	void CWE78_OS_Command_Injection__char_console_popen_45_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_68_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_10_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_01_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_06_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_02_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_42_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_65_bad();

	void CWE78_OS_Command_Injection__char_console_popen_32_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_05_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_02_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_13_bad();

	void CWE78_OS_Command_Injection__char_environment_system_04_bad();

	void CWE78_OS_Command_Injection__char_environment_system_11_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_14_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_12_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_16_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_32_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_22_bad();

	void CWE78_OS_Command_Injection__char_console_popen_34_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_41_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_05_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_68_bad();

	void CWE78_OS_Command_Injection__char_console_popen_68_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_09_bad();

	void CWE78_OS_Command_Injection__char_environment_system_61_bad();

	void CWE78_OS_Command_Injection__char_environment_system_18_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_10_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_14_bad();

	void CWE78_OS_Command_Injection__char_console_system_65_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_42_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_54_bad();

	void CWE78_OS_Command_Injection__char_environment_system_54_bad();

	void CWE78_OS_Command_Injection__char_console_system_44_bad();

	void CWE78_OS_Command_Injection__char_environment_system_15_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_22_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_08_bad();

	void CWE78_OS_Command_Injection__char_environment_system_09_bad();

	void CWE78_OS_Command_Injection__char_console_system_06_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_17_bad();

	void CWE78_OS_Command_Injection__char_console_system_17_bad();

	void CWE78_OS_Command_Injection__char_console_system_51_bad();

	void CWE78_OS_Command_Injection__char_console_system_08_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_17_bad();

	void CWE78_OS_Command_Injection__char_console_system_41_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_52_bad();

	void CWE78_OS_Command_Injection__char_environment_system_17_bad();

	void CWE78_OS_Command_Injection__char_console_popen_11_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_15_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_15_bad();

	void CWE78_OS_Command_Injection__char_environment_system_66_bad();

	void CWE78_OS_Command_Injection__char_environment_system_14_bad();

	void CWE78_OS_Command_Injection__char_environment_system_41_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_21_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_63_bad();

	void CWE78_OS_Command_Injection__char_console_system_53_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_06_bad();

	void CWE78_OS_Command_Injection__char_console_popen_21_bad();

	void CWE78_OS_Command_Injection__char_console_system_01_bad();

	void CWE78_OS_Command_Injection__char_environment_system_67_bad();

	void CWE78_OS_Command_Injection__char_environment_system_68_bad();

	void CWE78_OS_Command_Injection__char_console_system_21_bad();

	void CWE78_OS_Command_Injection__char_environment_system_13_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_61_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_45_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_15_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_04_bad();

	void CWE78_OS_Command_Injection__char_environment_system_08_bad();

	void CWE78_OS_Command_Injection__char_console_system_04_bad();

	void CWE78_OS_Command_Injection__char_console_popen_08_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_44_bad();

	void CWE78_OS_Command_Injection__char_console_popen_03_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_68_bad();

	void CWE78_OS_Command_Injection__char_environment_system_34_bad();

	void CWE78_OS_Command_Injection__char_console_popen_41_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_10_bad();

	void CWE78_OS_Command_Injection__char_console_popen_51_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_52_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_31_bad();

	void CWE78_OS_Command_Injection__char_environment_system_52_bad();

	void CWE78_OS_Command_Injection__char_console_system_63_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_66_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_66_bad();

	void CWE78_OS_Command_Injection__char_console_popen_04_bad();

	void CWE78_OS_Command_Injection__char_console_system_10_bad();

	void CWE78_OS_Command_Injection__char_console_popen_16_bad();

	void CWE78_OS_Command_Injection__char_console_popen_42_bad();

	void CWE78_OS_Command_Injection__char_console_system_11_bad();

	void CWE78_OS_Command_Injection__char_environment_system_32_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_65_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_07_bad();

	void CWE78_OS_Command_Injection__char_console_system_22_bad();

	void CWE78_OS_Command_Injection__char_console_popen_10_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_54_bad();

	void CWE78_OS_Command_Injection__char_console_system_15_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_31_bad();

	void CWE78_OS_Command_Injection__char_environment_system_44_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_45_bad();

	void CWE78_OS_Command_Injection__char_console_system_66_bad();

	void CWE78_OS_Command_Injection__char_environment_execlp_54_bad();

	void CWE78_OS_Command_Injection__char_console_system_32_bad();

	void CWE78_OS_Command_Injection__char_console_popen_01_bad();

	void CWE78_OS_Command_Injection__char_console_system_18_bad();

	void CWE78_OS_Command_Injection__char_environment_system_03_bad();

	void CWE78_OS_Command_Injection__char_environment_system_07_bad();

	void CWE78_OS_Command_Injection__char_console_popen_53_bad();

	void CWE78_OS_Command_Injection__char_console_popen_12_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_12_bad();

	void CWE78_OS_Command_Injection__char_environment_execl_03_bad();

	void CWE78_OS_Command_Injection__char_console_popen_14_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_51_bad();

	void CWE78_OS_Command_Injection__char_environment_system_22_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_16_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_07_bad();

	void CWE78_OS_Command_Injection__char_console_popen_67_bad();

	void CWE78_OS_Command_Injection__char_environment_popen_42_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
	namespace CWE78_OS_Command_Injection__char_environment_execlp_72 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_system_82 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_33 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_system_81 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_system_43 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_system_72 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_73 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_popen_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_73 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_system_82 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_system_81 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_popen_62 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_33 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_43 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_popen_33 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_62 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_81 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_popen_82 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_system_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_62 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_43 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_43 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_popen_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_82 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_popen_73 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_74 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_system_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_system_74 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_system_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_popen_72 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_popen_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_system_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_system_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_system_33 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_81 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_system_73 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_popen_43 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_system_74 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_74 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_82 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_system_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_popen_74 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_73 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_72 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_82 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_popen_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_81 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_system_62 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_system_84 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_62 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_72 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_system_72 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_74 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_system_73 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_popen_81 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_system_62 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_33 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_system_33 { void good();}

	namespace CWE78_OS_Command_Injection__char_console_system_43 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_system_83 { void good();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_84 { void good();}

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
	namespace CWE78_OS_Command_Injection__char_environment_execlp_72 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_system_82 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_33 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_system_81 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_system_43 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_system_72 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_73 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_popen_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_73 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_system_82 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_system_81 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_popen_62 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_33 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_43 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_popen_33 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_62 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_81 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_popen_82 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_system_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_62 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_43 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_43 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_popen_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_82 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_popen_73 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_74 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_system_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_system_74 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_system_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_popen_72 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_popen_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_system_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_system_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_system_33 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_81 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_system_73 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_popen_43 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_system_74 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_74 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_82 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_system_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_popen_74 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_73 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_72 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_82 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_popen_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execlp_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_81 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_system_62 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_system_84 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_62 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_72 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_system_72 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_74 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_system_73 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_popen_81 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_system_62 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_popen_33 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_system_33 { void bad();}

	namespace CWE78_OS_Command_Injection__char_console_system_43 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_system_83 { void bad();}

	namespace CWE78_OS_Command_Injection__char_environment_execl_84 { void bad();}

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
