// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE404_Improper_Resource_Shutdown__open_fclose_64_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_65_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_51_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_32_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_10_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_63_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_14_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_16_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_08_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_22_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_03_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_42_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_12_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_11_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_44_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_66_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_15_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_34_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_18_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_04_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_09_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_53_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_02_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_07_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_01_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_68_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_61_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_67_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_45_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_05_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_13_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_21_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_17_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_52_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_06_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_54_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_31_good();

	void CWE404_Improper_Resource_Shutdown__open_fclose_41_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE404_Improper_Resource_Shutdown__open_fclose_64_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_65_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_51_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_32_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_10_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_63_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_14_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_16_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_08_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_22_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_03_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_42_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_12_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_11_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_44_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_66_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_15_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_34_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_18_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_04_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_09_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_53_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_02_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_07_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_01_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_68_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_61_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_67_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_45_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_05_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_13_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_21_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_17_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_52_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_06_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_54_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_31_bad();

	void CWE404_Improper_Resource_Shutdown__open_fclose_41_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
	namespace CWE404_Improper_Resource_Shutdown__open_fclose_81 { void good();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_82 { void good();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_84 { void good();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_74 { void good();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_43 { void good();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_72 { void good();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_83 { void good();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_62 { void good();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_84 { void good();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_83 { void good();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_73 { void good();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_33 { void good();}

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
	namespace CWE404_Improper_Resource_Shutdown__open_fclose_81 { void bad();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_82 { void bad();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_84 { void bad();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_74 { void bad();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_43 { void bad();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_72 { void bad();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_83 { void bad();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_62 { void bad();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_84 { void bad();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_83 { void bad();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_73 { void bad();}

	namespace CWE404_Improper_Resource_Shutdown__open_fclose_33 { void bad();}

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
